### ISSUE TITLE
Support of GitHub app authentication for private checkouts

### ISSUE THREAD

**Issue by droidpl** [daspn/private-actions-checkout#11]
@daspn I am planning to work on this action in the upcoming week to add the possibility to use a GitHub app `app_id` and `private_key` to get a token that is able to checkout the repositories. As it is now, the ssh key requires users to have a personal ssh associated with the repos they want to checkout, and that is not scalable for an enterprise environment as it would require a machine account.

This is the change I am proposing on how it looks like:
```
name: Sample private checkout
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the private actions
        uses: org/private-actions-checkout
        with:
          repositories: "['company/action1@main', 'company/action2@v1']"
          folder: 'actions'
          app_id: ${{ secrets.checkout_app_id }}
          app_secret: ${{ secrets.checkout_app_secret }}
      - name: Use action 1
        uses: ./actions/company-action1
```

We can leave the support as is for the ssh key and make it optional, so people provide one or the other.

What are your thoughts?

Thanks for this nice action! ✨
