### ISSUE TITLE
checkout_base_path is not cleaned up

### ISSUE THREAD

**Issue by ollien** [daspn/private-actions-checkout#36]
In my workflow, I clone an action I want to use to a directory outside my base repository.

```yaml
      - name: Fetch Action
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["some/action"]'
          checkout_base_path: ./actions
          ssh_private_key: ${{ secrets.SSH_KEY }}
```

However, I'm running this on a self-hosted runner, rather than one of the ephemeral Github-provided ones. It seems that the cleanup step of this action does not take the `checkout_base_path` into consideration, and just cleans up some SSH related anomalies. As such, subsequent runs fail with

```
Error: Command failed: git clone --depth=1 --single-branch --branch main git@github.com:MyOrganization/my-action.git ./actions/my-action
fatal: destination path './actions/my-action' already exists and is not an empty directory.
```

It would be nice if (even optionally) this could be cleaned up afterwards.
